# Setup
title: Leo's Hub
description: A page for my notes
name: Leo's Hub
tagline: A responsive page for project on GitHub
baseurl: ""
locale: "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
