title: Leo's Hub
description: My Personal Hub
author: Leo Pham
github: https://github.com/hongthaipham
about: I'm a fullstack dev.
disqus_shortname: leogithubpage
google_analytics: UA-136143483-1
facebook_appId: 367729610488852
facebook_appVer: v3.2
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
  - icon: fa-facebook
    link: "https://www.facebook.com/hongthaipro"
  - icon: fa-twitter
    link: "https://twitter.com/leopham_it"
  - icon: fa-linkedin
    link: "https://www.linkedin.com/in/leo-pham-1208"
  - icon: fa-github
    link: "https://github.com/hongthaipham"

share:
  twitter_username: leopham_it
  fb_appid: 367729610488852

urls:
  - text: About Me
    url: /about/
  - text: My Projects
    url: /projects/
  - text: XML Feed
    url: /feed.xml

url: "https://hongthaipham.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ["development"]
